import json
from sklearn.cluster import k_means
from MDS import loadDataFromFile


if __name__ == '__main__':
    path = "./output_file_MDS.json"
    data = loadDataFromFile(path)

    outputData = {}

    for year in data:
        ids = []     # Store the ids
        labels = {}
        X = []
        for d in data[year]:
            ids.append(d)
            X.append(data[year][d])
        _, result, __ = k_means(X, 6)
        for index in range(len(result)):
            labels[ids[index]] = [
                X[index][0],                # x coordinate generated by MDS
                X[index][1],                # y coordinate generated by MDS
                int(result[index])          # the results of clustering generated by k-means
            ]
        outputData[year] = labels

    with open("./output_file_k-means.json", mode='w', encoding='utf8') as file:
        json.dump(outputData, file)

    pass
